### ISSUE TITLE
Chucklib-Livecode Manual Listing 9 Problem

### ISSUE THREAD

**Issue by clfest** [jamshark70/ddwChucklib-livecode#15] opened 2020-07-04 06:28 UTC
After a long time I am looking at the ddwChucklib-livecode quark again. I
am going through the Manual for this (February 9, 2020), whereas I
encounter this odd behavior on Listing 9.

/**************
 Listing 9. Multi-bar bassline.
 **************/

// If the bass doesn't exist, first do this:
/make(pbsVC:pbs/melBP:bs(octave:3));

/bars.(\bs, 2, \a);

/bs.a0 = "1>|4~5~7 | 4~|3'~";
/bs.a1 = " 5>~|6| 4~| 3";

/setupbars.(\bs, 2, \b);
...

I execute the (on Linux shft-enter) /make([pbs... line

Post window responds:

BP('bs')'s parameter map:
   acc: ( $>: 1, $.: 0, 'default': -, $-: 0 )
** degree: ( 'isPitch': true )
-> BP('bs')

then I execute the (on Linux shft-enter) /bars.(\bs, 2, \a);  line

Post window responds:

-> a Document

but now the document reads:

/
/bs.a0 = "";
/bs.a1 = "";bars.(\bs, 2, \a);

The Document window has CHANGED

What's the deal?

**Comment by jamshark70** [comment] 2020-07-04 11:37
> The Document window has CHANGED

Yes, that's right.

The `/bars` function creates several new empty phrases, with numbers (in the example, `a0` and `a1`).

The next thing you will want to do is to edit the phrases so that they contain sounding events. You could do this by typing the identifier for each phrase one by one, but that's slow in performance. So the function helps you by adding templates into the document, at the cursor position.

Currently it assumes the cursor is at the end of the `/bars...` line. If you do that, the document change will make more sense. That's a legit bug.

The point of live coding is interaction with the program while it's running -- interaction may include automated help writing parts of the program text that can be anticipated.

**Comment by jamshark70** [comment] 2021-10-07 03:11
Actually this is a duplicate of #8 -- closing this one.

**Closed by jamshark70** 2021-10-07 03:11 UTC
